export const actionTypes = {
    SET_EMAIL_VALUE: '@@registration/SET_INPUT_VALUE',
    SET_PASSWORD_VALUE: '@@registration/SET_PASSWORD_VALUE',
    SET_CONFIRM_VALUE: '@@registration/SET_CONFIRM_VALUE',
    SET_FIRSTNAME_VALUE: '@@registration/SET_FIRSTNAME_VALUE',
    SET_LASTNAME_VALUE: '@@registration/SET_LASTNAME_VALUE',
    SEND_REGISTRATION_REQUEST: '@@registration/SEND_REGISTRATION_REQUEST',
    SET_SUCCESS_VALUE: '@@registration/SET_SUCCESS_VALUE',
    CLEAR_INPUTS_VALUES: '@@registration/CLEAR_INPUTS_VALUES',
};
