export const actionTypes = {
  SET_VALUE: '@@chat/SET_VALUE',
  CONNECT: '@@chatCONNECT',
  PUT_ONLINE_USERS: '@@chat/PUT_ONLINE_USERS',
  PUT_MESSAGES: '@@chat/PUT_MESSAGES',
  PUT_NEW_MESSAGES: '@@chat/PUT_NEW_MESSAGES',
  SEND_NEW_MESSAGE: '@@chat/SEND_NEW_MESSAGE',
  GET_ALL_ROOMS: '@@chat/GET_ALL_ROOMS',
  SET_ALL_ROOMS: '@@chat/SET_ALL_ROOMS',
  GET_ALL_MESSAGES: '@@chat/GET_ALL_MESSAGES',
  SET_ALL_MESSAGES: '@@chat/SET_ALL_MESSAGES',
};
